"""AddPasswordResetEntity

Revision ID: 80531b347a28
Revises: 0d75f9125be7
Create Date: 2021-05-06 12:57:03.413648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80531b347a28'
down_revision = '0d75f9125be7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('passwordresets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_on', sa.DateTime(), nullable=False),
    sa.Column('updated_on', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('reset_code', sa.String(), nullable=False),
    sa.Column('expiry', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passwordresets_id'), 'passwordresets', ['id'], unique=False)
    op.create_index(op.f('ix_passwordresets_reset_code'), 'passwordresets', ['reset_code'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_passwordresets_reset_code'), table_name='passwordresets')
    op.drop_index(op.f('ix_passwordresets_id'), table_name='passwordresets')
    op.drop_table('passwordresets')
    # ### end Alembic commands ###
