"""AddNewFieldsToUserEntity

Revision ID: c50fcf792f16
Revises: b93af42f2a2d
Create Date: 2021-05-30 13:21:26.118683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c50fcf792f16'
down_revision = 'b93af42f2a2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('state', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'state')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
