"""AddAndModifyFieldsOnUserEntity

Revision ID: c660e719ce1d
Revises: c50fcf792f16
Create Date: 2021-07-31 01:06:54.741094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c660e719ce1d'
down_revision = 'c50fcf792f16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('instagram', sa.String(), nullable=True))
    op.alter_column('users', 'fname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'lname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'users', ['instagram'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'lname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'fname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('users', 'instagram')
    # ### end Alembic commands ###
