"""Remove fields from user entity

Revision ID: fd7a817af4e3
Revises: e59a39584091
Create Date: 2022-01-30 15:06:43.966815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd7a817af4e3'
down_revision = 'e59a39584091'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_instagram_key', 'users', type_='unique')
    op.drop_column('users', 'instagram')
    op.drop_column('users', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('instagram', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_instagram_key', 'users', ['instagram'])
    # ### end Alembic commands ###
